[build]
  base = "frontend"
  publish = "dist"
  command = "rm -rf node_modules/.cache && npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20.19.1"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Optimize build performance
  GENERATE_SOURCEMAP = "false"
  CI = "false"
  BUILD_TIMEOUT = "15"

# Proxy API requests to your backend API domain
[[redirects]]
  from = "/api/*"
  to = "https://oncosaferx-backend.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback so client-side routes work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, immutable"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=*, microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https://emfrwckxctyarphjvfeu.supabase.co https://oncosaferx-backend.onrender.com; frame-ancestors 'none'; object-src 'none'"

[context.production.environment]
  # Point this at your API base URL (override in Netlify UI if needed)
  VITE_API_URL = "/api"
  VITE_ENABLE_SERVER_ANALYTICS = "false"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-preview-api.example.com/api"
  VITE_ENABLE_SERVER_ANALYTICS = "false"
