[build]
  base = "frontend"
  publish = "dist"
  command = "rm -rf node_modules/.cache && rm -rf dist && rm -f .env && echo 'VITE_API_URL=/api' > .env && echo 'VITE_SUPABASE_URL=https://emfrwckxctyarphjvfeu.supabase.co' >> .env && echo 'VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZnJ3Y2t4Y3R5YXJwaGp2ZmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjM2NjcsImV4cCI6MjA3MzYzOTY2N30.yYrhigcrMY82OkA4KPqSANtN5YgeA6xGH9fnrTe5k8c' >> .env && echo 'VITE_DISABLE_SAMPLE_PATIENTS=true' >> .env && npm ci --legacy-peer-deps && npm run build && echo 'Static files in dist:' && (ls -la dist/*.html || ls -la dist || true)"

[build.environment]
  NODE_VERSION = "20.19.1"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Optimize build performance
  GENERATE_SOURCEMAP = "false"
  CI = "false"
  BUILD_TIMEOUT = "15"
  # Force cache bust for production fix - 2025-10-07T09:15:00Z  
  BUILD_TIMESTAMP = "2025-10-07T09:15:00Z"
  # Backend base URL for Edge proxy
  BACKEND_URL = "https://oncosaferx.onrender.com"

# API proxy via redirects (simpler approach)
[[redirects]]
  from = "/api/*"
  to = "https://oncosaferx-backend.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback so client-side routes work  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, immutable"

# Ensure HTML is always fresh so chunk hashes stay in sync
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=*, microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' blob:; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https://oncosaferx.onrender.com https://oncosaferx-backend.onrender.com https://emfrwckxctyarphjvfeu.supabase.co wss://emfrwckxctyarphjvfeu.supabase.co; worker-src 'self' blob:; frame-ancestors 'none'; object-src 'none'"

[context.production.environment]
  # Force API proxy usage for production
  VITE_API_URL = "/api"
  REACT_APP_API_URL = "/api"
  VITE_ENABLE_SERVER_ANALYTICS = "false"
  # Supabase configuration for frontend
  VITE_SUPABASE_URL = "https://emfrwckxctyarphjvfeu.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZnJ3Y2t4Y3R5YXJwaGp2ZmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjM2NjcsImV4cCI6MjA3MzYzOTY2N30.yYrhigcrMY82OkA4KPqSANtN5YgeA6xGH9fnrTe5k8c"
  # Prefer server-side auth proxy to avoid network timeouts
  VITE_SUPABASE_AUTH_VIA_PROXY = "true"
  VITE_DISABLE_SAMPLE_PATIENTS = "true"
  # Switch to Edge Functions for API proxy
  BUILD_ID = "restore-working-config-20251007-0915"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-preview-api.example.com/api"
  VITE_ENABLE_SERVER_ANALYTICS = "false"
