[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "rm -rf node_modules/.cache && rm -rf dist && rm -f .env && echo 'VITE_API_URL=/api' > .env && npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20.19.1"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Optimize build performance
  GENERATE_SOURCEMAP = "false"
  CI = "false"
  BUILD_TIMEOUT = "15"
  # Force cache bust for production fix - 2025-10-06T18:00:00Z
  BUILD_TIMESTAMP = "2025-10-06T18:00:00Z"

# API proxy handled by Edge Functions (see netlify/edge-functions/api-proxy.ts)

# SPA fallback so client-side routes work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, immutable"

# Ensure HTML is always fresh so chunk hashes stay in sync
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=*, microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https://emfrwckxctyarphjvfeu.supabase.co wss://emfrwckxctyarphjvfeu.supabase.co https://api.oncosaferx.com https://oncosaferx-backend.onrender.com; frame-ancestors 'none'; object-src 'none'"

[context.production.environment]
  # Force API proxy usage for production
  VITE_API_URL = "/api"
  REACT_APP_API_URL = "/api"
  VITE_ENABLE_SERVER_ANALYTICS = "false"
  # Switch to Edge Functions for API proxy
  BUILD_ID = "edge-functions-20251005-043000"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-preview-api.example.com/api"
  VITE_ENABLE_SERVER_ANALYTICS = "false"
