[build]
  base = "frontend"
  publish = "build"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[context.production.environment]
  REACT_APP_API_URL = "https://api.oncosaferx.com/api"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://api.oncosaferx.com/api"

