apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncosaferx-api
  labels:
    app: oncosaferx-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oncosaferx-api
  template:
    metadata:
      labels:
        app: oncosaferx-api
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/oncosaferx-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: SERVE_FRONTEND
              value: "true"
            - name: CORS_ORIGIN
              value: "https://yourdomain.com"
            - name: RATE_LIMIT_WINDOW_MS
              value: "900000"
            - name: RATE_LIMIT_MAX_REQUESTS
              value: "100"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

