apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oncosaferx-api
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: oncosaferx-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http

