image:
  repository: ghcr.io/OWNER/REPO
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - app.example.com
      secretName: app-example-com-tls

resources: {}

env:
  NODE_ENV: production
  SERVE_FRONTEND: "true"
  ENABLE_CSP: "true"
  ENABLE_HSTS: "true"
  CORS_ORIGIN: "https://app.example.com"

secrets:
  JWT_SECRET: ""
  SUPABASE_URL: ""
  SUPABASE_ANON_KEY: ""
  SUPABASE_SERVICE_ROLE_KEY: ""
  SENTRY_DSN: ""

replicaCount: 1
