name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install backend deps
        run: npm ci
      - name: Lint backend
        run: npm run lint --if-present
      - name: Test backend
        run: npm test --if-present
      - name: Install and build frontend
        run: |
          cd frontend
          npm ci
          # Create placeholder env file for CI build
          echo "VITE_SUPABASE_URL=https://placeholder.supabase.co" > .env.production
          echo "VITE_SUPABASE_ANON_KEY=placeholder-key" >> .env.production
          echo "VITE_SENTRY_DSN=" >> .env.production
          echo "VITE_SENTRY_ENV=ci" >> .env.production
          npm run build --if-present
      - name: Smoke check frontend assets and env embedding
        env:
          SMOKE_DIST_DIR: frontend/dist
          SMOKE_EXPECTED_SUPABASE_URL: https://placeholder.supabase.co
        run: npm run ci:smoke-frontend
      - name: Audit dependencies (high severity)
        run: npm audit --audit-level=high || true

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/amd64
          file: Dockerfile
          tags: oncosaferx/api:ci
          build-args: |
            VITE_SUPABASE_URL=https://placeholder.supabase.co
            VITE_SUPABASE_ANON_KEY=placeholder-key
            VITE_SENTRY_DSN=
            VITE_SENTRY_ENV=ci
          load: true
      - name: Run container smoke tests
        run: |
          set -euo pipefail
          docker run -d --rm --name osrx-ci -p 3000:3000 -e NODE_ENV=production oncosaferx/api:ci
          # wait for health
          for i in {1..30}; do
            if curl -fsS http://localhost:3000/health >/dev/null; then break; fi;
            sleep 1;
          done
          echo "API health:"
          curl -fsS http://localhost:3000/health | tee /dev/stderr | jq . >/dev/null 2>&1 || true
          # fetch index and extract first asset
          HTML=$(curl -fsS http://localhost:3000/)
          ASSET=$(echo "$HTML" | grep -Eo '/assets/[^"]+\.js' | head -n 1)
          if [ -z "$ASSET" ]; then echo "No asset script found in index" >&2; exit 1; fi
          echo "Testing asset: $ASSET"
          curl -fsS "http://localhost:3000$ASSET" >/dev/null
          # API health endpoint
          curl -fsS http://localhost:3000/api/health >/dev/null
          docker logs osrx-ci --since 1m || true
          docker stop osrx-ci

  docker-publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}
          build-args: |
            VITE_SUPABASE_URL=https://placeholder.supabase.co
            VITE_SUPABASE_ANON_KEY=placeholder-key
            VITE_SENTRY_DSN=
            VITE_SENTRY_ENV=ci
